version: "3"

services:
  php-apache:
    image: webdevops/php-apache:8.2
    container_name: php-apache
    ports:
      - "8080:80"
    volumes:
      - /home/zhina/amir/carproject:/app
    depends_on:
      - mysql
    networks:
      - my-net
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: amir
    volumes:
      - /home/zhina/amir/db:/var/lib/mysql
      - /home/zhina/amir:/home
    networks:
      - my-net
  phpmyadmin:
    image: phpmyadmin
    ports:
      - "8081:80"
    links:
      - "mysql:db"
    networks:
      - my-net

networks:
  my-net:
    driver: bridge